### ISSUE TITLE
Bot crash

### ISSUE THREAD

**Issue by TiBarification** [Halreis/Discord-SourceQuery#1]
Bot has been shutdown.
Log of bot messages:
```Logged in as SourceQuery

Task was destroyed but it is pending!
task: <Task pending coro=<crontab() running at bot.py:94> wait_for=<Future pending cb=[Task._wakeup()]>>```

**Comment by Halreis** [comment]
Not a direct issue w/ the bot itself, but it is either websockets are going down, or a high load that prevents it from responding on time.

Given the uptime (around 8 hours), I’d suppose it is related to websockets. Currently investigating.

**Comment by Halreis** [comment]
Couldn’t reproduce this bug, so I’m closing this down. It sounds like it was a random connection hiccup (which caused `bot.send_message` to not respond).
