### ISSUE TITLE
channel message

### ISSUE THREAD

**Issue by neoll4ik** [Halreis/Discord-SourceQuery#4]
hello, how can bot say message in channel, with channel id ?

**Comment by Halreis** [comment]
You should consult [discord.py’s docs](https://discordpy.readthedocs.io/en/latest/). In your case that would be [send_message()](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message). Depending on the destination, your channel’s class would vary from simple `Channel` to something more complicated.

Still, docs cover this topic quite well.

**Comment by neoll4ik** [comment]
Sorry, im too much stupid... newb on this world.
this default:
async def sendMessage(userid, listitem):
	user = discord.User(id=userid)
	await bot.send_message(user, "Some servers did not respond:\n```"+"\n".join(listitem)+"```")

i need to channel, so:
async def sendMessage(channelid, listitem):
	channel = discord.Channel(id=channelid)
	await client.send_message(discord.Object(id='12324234183172'), "Some servers did not respond:\n```"+"\n".join(listitem)+"```")

or something wrong?

**Comment by Halreis** [comment]
```py
async def sendMessage(dummy, listitem):
	channel = discord.Channel(id="ID_OF_YOUR_DESIRED_CHANNEL")
	await bot.send_message(channel, "Some servers did not respond:\n"+"\n".join(listitem)+"")
```

That _should_ do the trick. I did not test this code, but that should work, just replace `ID_OF_YOUR_DESIRED_CHANNEL` with the channel snowflake.

**Comment by neoll4ik** [comment]
i will test right now, one moment

**Comment by neoll4ik** [comment]
async def sendMessage(dummy, listitem):
        channel = discord.Channel(id="388393349876416512")
        await bot.send_message(channel, "Some servers did not respond:\n"+"\n".join(listitem)+"")

bot loaded, but cant send message:

Logged in as SourceQuery Bot

Task exception was never retrieved
future: <Task finished coro=<crontab() done, defined at bot.py:82> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 93, in crontab
    await sendMessage(key, value)
  File "bot.py", line 80, in sendMessage
    channel = discord.Channel(id="388393349876416512")
  File "/usr/local/lib/python3.5/dist-packages/discord/channel.py", line 89, in __init__
    self._update(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/channel.py", line 112, in _update
    everyone_id = self.server.id
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by Halreis** [comment]
Oh, yeah, right, one can’t simply construct a channel class. Gotta use `get_channel()` instead:

```js
async def sendMessage(dummy, listitem):
	channel = bot.get_channel(ID_OF_YOUR_DESIRED_CHANNEL)
	await bot.send_message(channel, "Some servers did not respond:\n"+"\n".join(listitem)+"")
```

**Comment by neoll4ik** [comment]
Task exception was never retrieved
future: <Task finished coro=<crontab() done, defined at bot.py:82> exception=InvalidArgument('Destination must be Channel, PrivateChannel, User, or Object. Received NoneType',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 93, in crontab
    await sendMessage(key, value)
  File "bot.py", line 81, in sendMessage
    await bot.send_message(channel, "Some servers did not respond:\n"+"\n".join(listitem)+"")
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 1145, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 289, in _resolve_destination
    raise InvalidArgument(fmt.format(destination))
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received NoneType


I change channel id, non private, wait msg, but i thing doesnt work

**Comment by neoll4ik** [comment]
Nope... in default channel bot do nohing. I try start server then /chek, server Responded.  Then stop server and wait more 5mins, try /check   status Didn’t respond. But in default channel no message, in console no errors.

**Comment by neoll4ik** [comment]
No, same error:
Task exception was never retrieved
future: <Task finished coro=<crontab() done, defined at bot.py:82> exception=InvalidArgument('Destination must be Channel, PrivateChannel, User, or Object. Received NoneType',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 93, in crontab
    await sendMessage(key, value)
  File "bot.py", line 81, in sendMessage
    await bot.send_message(channel, "Some servers did not respond:\n"+"\n".join(listitem)+"")
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 1145, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 289, in _resolve_destination
    raise InvalidArgument(fmt.format(destination))
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received NoneType

**Comment by neoll4ik** [comment]
I GOT IT 
Channel id   ('ID')  =) THX DUDE! its work!

**Comment by neoll4ik** [comment]
async def sendMessage(dummy, listitem):
	channel = bot.get_channel('ID_OF_YOUR_DESIRED_CHANNEL')
	await bot.send_message(channel, "Some servers did not respond:\n"+"\n".join(listitem)+"")
