### ISSUE TITLE
Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by neoll4ik** [Halreis/Discord-SourceQuery#5]
@Halreis Hello! i got new error.

Started bot 12hrs ago, 
now i got:

Logged in as ALTFS Servers-Info

Task was destroyed but it is pending!
task: <Task pending coro=<crontab() running at bot.py:93> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_connect_done(6)(), Task._wakeup()]>>

**Comment by neoll4ik** [comment]
but now, work fine, floating error...

What about add discription in db? 
Something like that:
/add  ip port description (/add 127.0.0.1 27017 Server 2 bla bla bla)

check and alert give  ip:port description.

Because have 20+ servers and dont remember all ip's  =)

**Comment by Halreis** [comment]
I’ve already had this issue with the prematurely destroyed task, but can’t reproduce it to this day. Probably has something to do with the connection. Either that or something related to the handling of asyncio looptasks.

> What about add discription in db?

You probably want to hand the task to someone who’s capable of working with python in your project’s team. You gotta have some basic python knowledge to implement that.

> and if use: python3 bot.py and close ssh session, bot just shutsown

That’s the intended behaviour. Either run it as a daemon or run it in an off-screen host (tmux or screen will do just fine).
